name: Python Code Analysis

on:
  push:
    branches:
      - branch1

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: pylint polymath.py

      - name: Run black
        run: black polymath.py
